INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00001','vie au campus','Q1','2020-10-02','12:34','A1','Visite du campus','Bonjour, je viens d"arriver et je n"arrive pas à trouver mes salles de cours, j"aurai besoin d"une personne pour me faire visiter le campus ','B1','D2211');
INSERT INTO Question (idQ, categorie,idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00002','Enseignements','Q2','2020-10-02','13:22','A1','Cours L2 MAth','Bonjour, il y aurait une personne en L2 Mathematique qui pourrait me passer les cours que j"ai raté depuis la rentrée à maintenant svp ? Je viens d"arriver et je suis très en retard. Merci !','B1','D2243');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00003','Projet L3 Informatique','Q3','2020-10-05','18:13','A2','Projet L3 Informatique','Bonjour, je ne sais pas comment se passent les projets de ce semestre je viens d"arriver et je ne sais pas comment faire, j"aimerai aussi trouver un groupe pour le projet de developpement web. Bonne journée ! ','B2','D2541');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00004','Enseignements','Q4','2020-10-10','14:48','A2','CC Droit Constitutionnel','Bonjour, j"aimerai savoir si quelqu"un était disponible pour me faire un petit récapitulatif de ce qui a été vu jusqu"à présent en Droit Constitutionnel, j"ai un CC la semaine prochaine mais je viens d"arriver :(','B2','D2114');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00005','Révisions','Q5','2020-10-13','08:07','A1','Demande de révisions régulières','Salut ! Je suis en L1 mais à cause de la situation sanitaire je n"ai pas pu arriver à temps en France pour assister au début de mes cours, j"aimerai donc savoir s"il y avait quelqu"un de disponible pour des révisions régulières pour pouvoir rattraper mon retard. Merci d"avance ! ','B3','D2789');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00006','Outils de travail','Q6','2020-10-28','22:17','A2','Teams et emploi du temps','Hey ! J"aurai besoin d"aide pour comprendre mon emploi du temps et le fonctionnement de Teams, je n"ai pas l"habitude de travailler avec cet outils. Bonne journée à vous !','B1','D2214');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00007','Enseignements','Q7','2020-11-06','16:21','A1','Cours L1 Math','Bonjour ! Est-ce que quelqu"un pourrait me fournir les cours fait jusqu"à présent, je suis assez en retard et assez timide j"ai du mal à aller vers mse camarades pour leur demander de l"aide alors je préfère faire ça dérrière un ecran. Merci d"avance à celui ou celle qui repondra !','B3','D2336');
INSERT INTO Question (idQ, categorie, idMessage, dateMess, heureMess, admAjout, titreQ, contenuQ, id_borne, idDem) VALUES ('00008','Révisions','Q8','2020-11-28','10:36','A2','Révisions avant exams','Bonjouuuur, vu que les exams finaux arrivent, j"avoue qu"avec la rentrée tardive que j"ai fait je me retrouve très en retard dans mes révisions. Quelqu"n serait disponible pour réviser avec moi avant les exams ?','B1','D2219');

